// vc-client/src/routes/login/+page.svelte
<section class="dark:bg-white flex justify-center items-center py-20">
	<div
		class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700"
	>
		<form class="space-y-6" action="#">
			<h5 class="text-xl font-medium text-gray-900 dark:text-white">Log in to Varchess</h5>
			<div>
				<label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Your email/username</label
				>
				<input
					type="email"
					name="email"
					id="email"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
					placeholder="email or username"
					required
				/>
			</div>
			<div>
				<label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
					>Your password</label
				>
				<input
					type="password"
					name="password"
					id="password"
					placeholder="••••••••"
					class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
					required
				/>
			</div>
			<div class="flex items-start">
				<div class="flex items-start">
					<div class="flex items-center h-5">
						<input
							id="remember"
							type="checkbox"
							value=""
							class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800"
							required
						/>
					</div>
					<label for="remember" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
						>Remember me</label
					>
				</div>
				<a href="#" class="ml-auto text-sm text-blue-700 hover:underline dark:text-blue-500"
					>Forgot Password?</a
				>
			</div>
			<button
				type="submit"
				class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
				>Login to your account</button
			>
			<div class="text-sm font-medium text-gray-500 dark:text-gray-300">
				Not registered? <a href="#" class="text-blue-700 hover:underline dark:text-blue-500"
					>Create account</a
				>
			</div>
		</form>
	</div>
</section>

// vc-frontend/src/pages/Login.vue
<template>
    <q-page class="bg-custom row justify-center items-center">
    <div >
      <div class="row">
        <div class="text-h4 text-white q-my-md">Login to Varchess</div>
      </div>
      <div class="row">
        <q-card rounded bordered class="q-pa-md shadow-1 card-props" >
          <q-card-section>
            <q-form class="q-gutter-md">
              <q-input square filled clearable v-model="username" type="email" label="username" />
              <q-input square filled clearable v-model="password" type="password" label="password" />
            </q-form>
          </q-card-section>
          <q-card-actions class="q-px-md">
            <q-btn unelevated color="light-green-8" size="lg" class="full-width" label="Login" />
          </q-card-actions>
          <q-card-section class="text-center q-pa-none">
            <p class="text-grey-6">Not registered? <p @click="redirectToSignup" style="cursor: pointer;">Create an Account</p></p>
          </q-card-section>
        </q-card>
      </div>
    </div>
  </q-page>
</template>

<script lang="ts">
import {ref} from 'vue'
import { useRouter } from 'vue-router';

export default{
    setup(){
        const username = ref(null)
        const password = ref(null)
        
        const router = useRouter();
        const redirectToSignup = ()=>{
          router.push({name:'Signup'})
        }

        return {
            username,
            password,
            onSubmit(){
            },
            onReset () {
                username.value = null
                password.value = null
            },
            redirectToSignup
        }
    }
}
</script>

<style scoped>
.bg-gradient{
    background: linear-gradient(
       128deg,
       rgba(64, 76, 255, 1) 0%,
       rgba(174, 63, 255, 1) 100%
     );
}

.bg-custom{
    background: #531ab4;
}
.card-props{
    width: 25rem;
    border-radius: 20px;
}
</style>
